name: Custom Checkout
description: Buildkite plugin for flexible repository checkout, including cross-repository triggers
author: https://github.com/Test
requirements: []
configuration:
  properties:
    skip_checkout:
      type: boolean
    build_checkout_path:
      type: string
    delete_checkout:
      type: boolean
    interpolate_checkout_path:
      type: string
    custom_repo:
      type: string
    repos:
      type: array
      items:
        type: object
        properties:
          config:
            type: array
            items:
              type: object
              properties:
                url:
                  type: string
                ref:
                  type: string
                ssh_key_path:
                  type: string
                clone_flags:
                  anyOf:
                    - type: string
                    - type: array
                      items:
                        type: string
              additionalProperties: false
            required:
              - url
        additionalProperties: false
      required:
        - config
  additionalProperties: false
