name: Custom Checkout
description: Specify a custom Git repository, branch, or commit to checkout
author: https://github.com/saah13
requirements:
  - git
configuration:
  properties:
    repository:
      type: string
    branch:
      type: string
    commit:
      type: string
  required:
    - repository
