#!/usr/bin/env bash

set -eo pipefail

function log_info {
  echo "$1"
}

function log_error {
  echo "$1"
}

function remove_directory {
  local dir=$1
  rm -rf "$dir" 2>/dev/null || {
    log_error "Tried running: rm -rf $dir"
    log_error "But it failed leaving the following files as residue"
    ls -la "$dir"
  }
}

function remove_directory_with_sudo {
  local dir=$1
  sudo -n rm -rf "$dir" || {
    log_error "Tried running: sudo -n rm -rf $dir"
    log_error "But it failed leaving the following files as residue"
    ls -la "$dir"
  }
}

function cleanup_checkout_directory {
  local dir=$1
  if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" || "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_DELETE_CHECKOUT" != "true" ]]; then
    exit 0
  fi

  log_info "Removing checkout directory: $dir"
  remove_directory "$dir"

  if [ -d "$dir" ]; then
    log_info "Attempting to cleanup with sudo"
    remove_directory_with_sudo "$dir"
  fi

  if [ ! -d "$dir" ]; then
    log_info "Cleanup completed successfully."
  else
    log_error "Cleanup was not successful."
  fi
}

cleanup_checkout_directory "$BUILDKITE_BUILD_CHECKOUT_PATH"
